### PR TITLE
Serial File Opening

### LINKED ISSUE #536: ipfs add opening too many files
I wanted to test out some of what ipfs could do, so i decided to add the entire go-ipfs directory, recursively. Ipfs wasnt too happy (or rather, my OS wasnt too happy with ipfs)

```
whyrusleeping@alarm ~/g/s/g/j/go-ipfs> ipfs add -r .
Error: open exchange/bitswap/testnet/interface.go: too many open files
```

### PR DESCRIPTION
**Pull request by mappum**
This resolves #536.

It creates a new kind of `commands.File` called SerialFile, which only needs to open one `os.File` at a time. It's hella clean since it handles all of the file opening/closing on its own.

### CODE REVIEW

File: commands/files/readerfile.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+func (f *ReaderFile) FileName() string {
+	return f.Filename
+}
+
+func (f *ReaderFile) Read(p []byte) (int, error) {
+	return f.Reader.Read(p)
+}
+
+func (f *ReaderFile) Close() error {
```
Comment (briantigerchow) [inline commands/files/readerfile.go]: It's better to accept a ReadCloser and allow clients to wrap their Readers in a Closer wrapper (that has no effect). 

Secretly introspecting and closing a client's Reader is harder to explain to callers and can result in surprising behavior.

Comment (jbenet) [inline commands/files/readerfile.go]: yeah i got bitten by this :/ -- i've since stopped doing it. it's also fine to leave closing to the user in many cases.

Comment (briantigerchow) [inline commands/files/readerfile.go]: just for the record the NopCloser is here:

```Go
package ioutil

func NopCloser(r io.Reader) io.ReadCloser
```
file:///Users/btc/Library/Application%20Support/Dash/DocSets/Go/Go.docset/Contents/Resources/Documents/golang.org/pkg/io/ioutil/index.html#NopCloser

**Comment by hmeine** [comment]
Strange, I am just starting to play around with ipfs, and apparently got exactly this error:
```
ERRO[20:25:47:000] open /Users/hmeine/.ipfs/blocks/1220c6bc/put-911313602: too many open files  module=commands/http
```
This was with ```ipfs add -r <some_dir>```, after roughly a dozen files (and at least two subdirectories being discovered).
I installed ipfs today, using ```go get -u github.com/ipfs/go-ipfs/cmd/ipfs```, and ```ipfs version``` states 0.3.8-dev, so I expect the above changes to be in my version?
Should I (as a beginner) rather install a release version?  Having go installed (disclaimer: I have no experience with it, though), and being familiar with Git and OSS development, I preferred the latest version.  Is that considered much more bleeding edge / unstable than the bundled downloads?

**Comment by whyrusleeping** [comment]
@hmeine continue discussion on https://github.com/ipfs/go-ipfs/issues/1689
